# Generated by Django 3.0.4 on 2020-09-14 15:38

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crispr_lib', '0002_auto_20200806_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='crispr',
            name='ccds_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='crispr',
            name='gene_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='crispr',
            index=django.contrib.postgres.indexes.GinIndex(fields=['gene_search', 'ccds_search'], name='crispr_lib__gene_se_57b7c6_gin'),
        ),
    ]
