# Generated by Django 3.0.4 on 2020-08-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('problem', models.CharField(max_length=500, verbose_name='Problem Title')),
                ('detail', models.TextField(verbose_name='Problem Details')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('category', models.IntegerField(choices=[(1, 'Genome-wide Crispr Library')], default=1, verbose_name='Category')),
                ('solved', models.BooleanField(default=False, verbose_name='Solved')),
                ('marked', models.BooleanField(default=False, verbose_name='Marked')),
            ],
        ),
    ]
