# Generated by Django 3.0.4 on 2020-08-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.IntegerField(choices=[(0, 'General'), (1, 'Genome-wide Crispr Library')], default=1, verbose_name='Category'),
        ),
    ]
